import type { Program } from "./types";

export const programs: Program[] = [
  {
    id: "ai-learner",
    title: "AI Learner / Student Programs",
    audience: "Class 6-12 students, schools, and parents",
    format: "2-day live online bootcamp + 1 year of monthly mentor guidance",
    outputs: [
      "3-4 projects",
      "AI tools exposure",
      "Challenge entry",
      "Certificate",
      "Prompt/toolkit resources",
    ],
    status: "needs verification",
    source: "assets/raw/AI Learner Program - Wasabi AI _compressed.pdf",
    cta: { label: "Ask about AI Learner", href: "/#contact", variant: "secondary" },
  },
  {
    id: "school-movements",
    title: "School and City-Wide AI Movements",
    audience: "Schools, students, civic/institutional partners",
    format: "City or district movement, event, or championship structure",
    outputs: [
      "Student builder participation",
      "School ecosystem visibility",
      "Projected event proof only until verified",
    ],
    status: "projected",
    source: "assets/raw/KASC Brochure_compressed.pdf",
    cta: { label: "Discuss a school program", href: "/#contact", variant: "secondary" },
  },
  {
    id: "shg-enterprise",
    title: "AI Empowerment for SHG Ecosystems",
    audience: "SHG women and EFC leaders",
    format: "Phased workshops, practice gaps, regional-language, voice-first",
    outputs: [
      "Prompt handbooks",
      "Product stories",
      "WhatsApp catalog",
      "Packaging ideas",
      "Pricing/profit calculations",
      "Growth plan",
    ],
    status: "needs verification",
    source: "assets/raw/AI for SHG Empowerment_compressed.pdf",
    cta: { label: "Discuss SHG programs", href: "/#contact", variant: "secondary" },
  },
  {
    id: "public-empowerment",
    title: "Public-Sector Community Empowerment",
    audience: "SCBC students, women SHG leaders, persons with physical disability",
    format: "6-hour proof-of-concept with learning, building, and certification",
    outputs: ["First real solution", "Workflow", "Portfolio proof"],
    status: "needs verification",
    source: "assets/raw/Wasabi x Haryana SCBC- MoSJE_compressed.pdf",
    cta: { label: "Explore a pilot", href: "/#contact", variant: "secondary" },
  },
  {
    id: "builder-events",
    title: "Startup and Hackathon Builder Programs",
    audience: "Young builders, startup learners, hackathon participants",
    format: "Multi-session startup program or 1-day hackathon",
    outputs: ["MVP", "Workflow", "Website/app", "Pitch", "Prototype"],
    status: "needs verification",
    source:
      "assets/raw/Startup with AI Event Brochure.pdf; assets/raw/Bharat Builds with Manus AI - campaign_compressed.pdf",
    cta: { label: "Plan a builder event", href: "/#contact", variant: "secondary" },
  },
  {
    id: "co-branded-bootcamps",
    title: "College-Readiness and Co-Branded Bootcamps",
    audience: "College-bound students and platform partners",
    format: "5 days, 90 minutes per day",
    outputs: [
      "Prompt library",
      "Study kit",
      "Resume/LinkedIn",
      "Portfolio website",
      "AI content",
      "Workflow",
      "Web app",
      "Roadmap",
      "Certificate",
    ],
    status: "needs verification",
    source: "assets/raw/Adda247AIBootcampByWasabiAI_compressed.pdf",
    cta: { label: "Discuss co-branded work", href: "/#contact", variant: "secondary" },
  },
];
